package cn.zuel.wlyw.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTheme<M extends BaseTheme<M>> extends Model<M> implements IBean {

	public void setTId(java.lang.Integer tId) {
		set("t_id", tId);
	}
	
	public java.lang.Integer getTId() {
		return getInt("t_id");
	}

	public void setTName(java.lang.String tName) {
		set("t_name", tName);
	}
	
	public java.lang.String getTName() {
		return getStr("t_name");
	}

	public void setTAddtime(java.util.Date tAddtime) {
		set("t_addtime", tAddtime);
	}
	
	public java.util.Date getTAddtime() {
		return get("t_addtime");
	}

	public void setTUpdatetime(java.util.Date tUpdatetime) {
		set("t_updatetime", tUpdatetime);
	}
	
	public java.util.Date getTUpdatetime() {
		return get("t_updatetime");
	}

}
