package cn.zuel.wlyw.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAlbum<M extends BaseAlbum<M>> extends Model<M> implements IBean {

	public void setAId(java.lang.Integer aId) {
		set("a_id", aId);
	}
	
	public java.lang.Integer getAId() {
		return getInt("a_id");
	}

	public void setAUId(java.lang.Integer aUId) {
		set("a_u_id", aUId);
	}
	
	public java.lang.Integer getAUId() {
		return getInt("a_u_id");
	}

	public void setATId(java.lang.Integer aTId) {
		set("a_t_id", aTId);
	}
	
	public java.lang.Integer getATId() {
		return getInt("a_t_id");
	}

	public void setAName(java.lang.String aName) {
		set("a_name", aName);
	}
	
	public java.lang.String getAName() {
		return getStr("a_name");
	}

	public void setADesc(java.lang.String aDesc) {
		set("a_desc", aDesc);
	}
	
	public java.lang.String getADesc() {
		return getStr("a_desc");
	}

	public void setAAuth(java.lang.Integer aAuth) {
		set("a_auth", aAuth);
	}
	
	public java.lang.Integer getAAuth() {
		return getInt("a_auth");
	}

	public void setAAddtime(java.util.Date aAddtime) {
		set("a_addtime", aAddtime);
	}
	
	public java.util.Date getAAddtime() {
		return get("a_addtime");
	}

	public void setAUpdatetime(java.util.Date aUpdatetime) {
		set("a_updatetime", aUpdatetime);
	}
	
	public java.util.Date getAUpdatetime() {
		return get("a_updatetime");
	}

}
