package cn.zuel.wlyw.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseImage<M extends BaseImage<M>> extends Model<M> implements IBean {

	public void setIId(java.lang.Integer iId) {
		set("i_id", iId);
	}
	
	public java.lang.Integer getIId() {
		return getInt("i_id");
	}

	public void setIAId(java.lang.Integer iAId) {
		set("i_a_id", iAId);
	}
	
	public java.lang.Integer getIAId() {
		return getInt("i_a_id");
	}

	public void setIName(java.lang.String iName) {
		set("i_name", iName);
	}
	
	public java.lang.String getIName() {
		return getStr("i_name");
	}

	public void setIPath(java.lang.String iPath) {
		set("i_path", iPath);
	}
	
	public java.lang.String getIPath() {
		return getStr("i_path");
	}

	public void setIAddtime(java.util.Date iAddtime) {
		set("i_addtime", iAddtime);
	}
	
	public java.util.Date getIAddtime() {
		return get("i_addtime");
	}

	public void setIUpdatetime(java.util.Date iUpdatetime) {
		set("i_updatetime", iUpdatetime);
	}
	
	public java.util.Date getIUpdatetime() {
		return get("i_updatetime");
	}

}
