package cn.zuel.wlyw.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("admin", "a_id", Admin.class);
		arp.addMapping("album", "a_id", Album.class);
		arp.addMapping("image", "i_id", Image.class);
		arp.addMapping("theme", "t_id", Theme.class);
		arp.addMapping("user", "u_id", User.class);
	}
}

