package cn.zuel.wlyw.model;

import cn.zuel.wlyw.model.base.BaseAlbum;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Album extends BaseAlbum<Album> {
	public static final Album dao = new Album().dao();
}
