package cn.zuel.wlyw.model;

import cn.zuel.wlyw.model.base.BaseImage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Image extends BaseImage<Image> {
	public static final Image dao = new Image().dao();
}
