package cn.zuel.wlyw.model;

import cn.zuel.wlyw.model.base.BaseTheme;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Theme extends BaseTheme<Theme> {
	public static final Theme dao = new Theme().dao();
}
